version: "3"

services:
  back:
    image: ghcr.io/usacoasts/echo-backend-v5-alpha:pr-5
    volumes:
      # - ./app:/go/src/app
      - ./app/:/app/
    ports:
      - "5566:8080"
      - "2355:2345"
    stdin_open: true
    tty: true #コンテナ永続化
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
    depends_on:
      - mysql
    networks:
      - go2-network

  mysql:
    container_name: mysql2
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--skip-character-set-client-handshake', '--default-authentication-plugin=mysql_native_password']
    image: mysql:8.0
    restart: always
    volumes:
      - db-data:/var/lib/mysql
      - ./conf/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - go2-network
    environment:
      - MYSQL_DATABASE=echo
      - MYSQL_ROOT_PASSWORD=golang
      - MYSQL_USER=echo
      - MYSQL_PASSWORD=golang
      - TZ=Asia/Tokyo
    ports:
      - "3366:3306"

networks:
  go2-network:
    driver: bridge

volumes: # データの永続化
  db-data:
    driver: local